### PR TITLE
Implement GitHub PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
**FIX** #76 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes #<issue-number>` or `Fixes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@prajapatihet

### CODE REVIEW

**Comment by smog-root** [comment]
@prajapatihet merge it!

**Comment by prajapatihet** [comment]
Your workflow does not work in your PR
Make it correct PR once

**Comment by prajapatihet** [comment]
You can make PR template that compatiable with you PR checker

**Comment by smog-root** [comment]
Okay I will work on it!!

**Comment by smog-root** [comment]
I don't work on mine. But it works on other future PRs. Can you merge it now. I will work on it after sometime!!

**Comment by smog-root** [comment]
I have some pending issue in other repos!!

**Comment by smog-root** [comment]
I will make it in python. yaml! File!

**Comment by smog-root** [comment]
I have done a python version too. Merge what ever you like!!

Don't forget to add labels!

**Pull request closed without merging**
