### PR TITLE
Added Feature #60

### PR DESCRIPTION
**Pull request by ezsarthak**
I have added this feature.
Now we can see a great animation in the bottom navigation bar and a transition effect
Please add level3 label

https://github.com/user-attachments/assets/3e8e3f70-352a-4a33-a5ae-ab8f3d0d6b65

### CODE REVIEW

**Comment by ezsarthak** [comment]
I have used a package for bottom navigation bar. How to solve conflict error?

**Comment by prajapatihet** [comment]
first fetch the new code from main repo then try to raise PR
and delete pubspec.lock file and regenerate it

**Comment by ezsarthak** [comment]
Done

**Review by prajapatihet — APPROVED** [review]

**Comment by ezsarthak** [comment]
Sir I have a request, l am a new contributor to GSSOC'24 and have been contributing to this project. However, I have reached the points cap for Level 1, and as I don't have other projects left in my area of expertise, I would like to request a Level 2 tag so I can continue contributing and raise my total points

**Comment by ezsarthak** [comment]
Thank You !!

**Pull request merged**
