### PR TITLE
added the Search Page features

### PR DESCRIPTION
**Pull request by singhtrivendra**
i have added new forder name search which contain widgets form bankform and donors forms and below that search_screen file.
and i replace the 2nd home screen page with search screen page in homepge in pages widgets
you can see it from video given it.

https://github.com/user-attachments/assets/96428631-cd86-4927-925e-c0a63e559655

### CODE REVIEW

**Comment by singhtrivendra** [comment]
@prajapatihet  kindly Merge my PR and provide the level please i have spent lot of time to make changes

**Comment by singhtrivendra** [comment]
@prajapatihet please merge this PR and give it right level

**Review by prajapatihet — CHANGES_REQUESTED** [review]
Keep google_sign_in dependency and pull the latest updated code from remote repo if you haven't

**Comment by singhtrivendra** [comment]
@prajapatihet  plz. merger this pr .. conflict resolved and added  google_sign_in dependency in yml

**Review by prajapatihet — APPROVED** [review]

**Pull request merged**
