### PR TITLE
Fixed #59

### LINKED ISSUE #59: [Feature Request]: Displaying messages on Login Screen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

when the user enters already-used mail it should show the message "User already exists with this mail"
when the user enters the wrong password/email it should show the message "Wrong password/email entered"

### Use Case

when the user enters already-used mail it should show the message "User already exists with this mail"
when the user enters the wrong password/email it should show the message "Wrong password/email entered"

### Benefits

Good User experience 

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC Ext'24 contributor
- [X] I'm a Hacktoberfest 2024 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by ezsarthak**
Fixed #59 

Now the app displays a message when the user enters the wrong email or password 
image

When the user tries to signup using an already-used email
image

### CODE REVIEW

**Review by ezsarthak — COMMENTED** [review]
Fixed #59

**Review by prajapatihet — APPROVED** [review]

**Comment by ezsarthak** [comment]
Please add Hacktoberfest-accepted label
@prajapatihet

**Comment by ezsarthak** [comment]
Sir, I have a request, l am a new contributor to GSSOC'24 and have been contributing to this project. However, I have reached the points cap for Level 1, and as I don't have other projects left in my area of expertise, I would like to request a Level 2 tag so I can continue contributing and raise my total points

**Comment by prajapatihet** [comment]
according to complexity of your PR i can't assign higher level than current

**Pull request merged**
