### PR TITLE
changed form styling and and save button styling in profile screen

### PR DESCRIPTION
**Pull request by singhtrivendra**
phot
i have changed the form on profile screen and syling and color was not correct i used theme color and styling .

### CODE REVIEW

**Comment by singhtrivendra** [comment]
i have changed the form on profile screen and syling and color was not correct i used theme color and styling .

**Comment by singhtrivendra** [comment]
i have changed the form on profile screen and syling and color was not correct i used theme color and styling .

**Comment by singhtrivendra** [comment]
@mehul-m-prajapati kindly merge this pr

**Comment by mehul-m-prajapati** [comment]
I am not the owner of this repo.

**Review by prajapatihet — APPROVED** [review]

**Pull request merged**
