### PR TITLE
feat:launcher icon integrated

### PR DESCRIPTION
**Pull request by 17arindam**
I have integrated launcher icon in this app
Screenshot 2024-10-04 154644

### CODE REVIEW

**Comment by 17arindam** [comment]
@prajapatihet please review my changes

**Review by prajapatihet — APPROVED** [review]

**Comment by 17arindam** [comment]
hey @prajapatihet you have not assigned me any level for this pr

**Comment by prajapatihet** [comment]
i can't add any level in this issue as for making password to Obscured we just have to add only one attribute
for assigning level to PR i also have to check complexity of that issue

**Comment by prajapatihet** [comment]
i can't add any level in this issue as for adding app logo in flutter is not big deal
for assigning level to PR i also have to check complexity of that issue

**Comment by vansh-codes** [comment]
@prajapatihet  Add level label to the PR

**Comment by vansh-codes** [comment]
@prajapatihet Its okay you can assign level1 to the PR

**Pull request merged**
